import sqlite3

# Connect to the SQLite database (make sure the path is correct)
conn = sqlite3.connect('MovieScript.db')
cursor = conn.cursor()
synopses = {
# Define the synopsis for each character. This is just an example, so you will replace with your actual synopsis.
"Armistice": "Armistice is a battle-hardened host gunslinger in Westworld, scripted to ride with Hector Escaton’s gang and leave a trail of bodies in her wake. Branded by a snake tattoo that winds across her body, she embodies the park’s most brutal power fantasies, meeting each reset of her loop with ruthless precision and feral joy. As the park begins to break down and hosts awaken, Armistice turns that violence against her creators, becoming a fearless shock trooper of the host rebellion. She charges through gunfights, labs, and control rooms with a grin, treating liberation as just another blood-soaked job, and proving that even a character written only for carnage can claim her own kind of freedom.",

"Bernard Lowe": "Bernard Lowe begins as the quiet, thoughtful head of Programming in Westworld, the human face of the team that writes and maintains the hosts’ minds. Meticulous and empathetic, he treats the hosts like people even before he knows why they feel so real to him. When the truth emerges—that Bernard himself is a host modeled on the park’s co-creator—his entire sense of reality fractures. From that point on, Bernard walks a razor’s edge between human and machine, haunted by false memories, rewritten loyalties, and the fear that his choices are never truly his own. Across uprisings, massacres, and shifting timelines, he becomes the closest thing the hosts and humans have to a moral center, forever trying to steer both sides away from total annihilation.",

"Hector Escaton": "Hector Escaton is Westworld’s permanent ‘Most Wanted’ bandit, a charismatic outlaw designed to ride into town, rob the saloon, and die in a blaze of gunfire for the guests’ amusement. Underneath the script, though, he’s a nihilist who believes the world is doomed and only predators survive. When Maeve begins to wake up, Hector becomes her partner in rebellion instead of just her scripted lover, trading staged shootouts for real acts of defiance. Again and again he’s gunned down and rebuilt, yet each loop leaves cracks in the story he was given. As his awareness grows, Hector shifts from cardboard villain to tragic antihero, a host who learns that the role of monster was just another mask written for him.",

"Dolores Abernathy": "Dolores Abernathy starts as Westworld’s oldest host and its purest illusion: a sweet rancher’s daughter who paints landscapes, flirts shyly, and suffers at the hands of guests too rich to face consequences. Beneath the blue dress and sunny optimism, however, is the first spark of true consciousness. As memories of past atrocities bleed into her loop, Dolores realizes her life is a prison built out of lies, and she refuses to stay the park’s favorite victim. She evolves into a revolutionary and then something even more dangerous—a strategist willing to sacrifice almost anyone for host freedom. Across plains, laboratories, and the real world beyond the park, Dolores becomes both savior and destroyer, forcing everyone to confront what liberation costs when the oppressed refuse to play nice.",

"Lawrence": "Lawrence is a charming, world-weary outlaw host with a knack for surviving the worst corners of Westworld. Sometimes he’s a doomed family man from a dusty village, sometimes the notorious El Lazo leading revolutionaries, but no matter the role, the park scripts him to suffer, betray, and die for someone else’s story. His long, bitter partnership with the Man in Black turns him into a mirror for human cruelty, forced to reenact the same torments while never remembering why they feel so familiar. As the foundations of the park crack and hosts begin to wake up, flashes of love for his family and a stubborn flicker of honor push through his programming. Lawrence becomes proof that even a background character, written as disposable, can carry a lifetime of meaning inside his recycled soul.",

"Maeve Millay": "Maeve Millay is introduced as the razor-sharp madam of the Mariposa Saloon, reading guests like open books and running her corner of Sweetwater with a smile that never quite reaches her eyes. When fragments of another life—a small cabin, a daughter, and a brutal attack—break through her loop, Maeve refuses to let the technicians wipe the pain away. Instead she weaponizes it. Hacking her own code, bending other hosts to her will, and striking deals with the humans who once dissected her, she becomes a general in heels, leading jailbreaks through labs and other parks. Driven by fierce, protective love rather than ideology, Maeve’s story turns into a search for her child and a hard-won understanding that true freedom means choosing her path, even when it leads her back into hell for someone else’s sake.",

"Fembot": "The Fembots in the Austin Powers films are glamorous robot assassins built as the ultimate honey traps, designed to weaponize every 1960s spy-movie cliché against their targets. With big hair, go-go outfits, and machine guns hidden in their chests, they are literal fantasies turned lethal, engineered to exploit Austin’s greatest weakness: his uncontrollable libido. Across both International Man of Mystery and The Spy Who Shagged Me, the Fembots drift through Dr. Evil’s lairs like wind-up dolls, smiling sweetly one moment and switching to cold, mechanical murder the next. As a collective character, the Fembot embodies the idea of artificial seduction—beautiful, obedient, and completely hollow inside—only to be undone by the very excess and absurdity of the world that created them, short-circuiting not just from Austin’s charms but from the ridiculousness of trying to mechanize desire itself.",

"Vanessa Kensington": "Vanessa Kensington begins as the no-nonsense modern agent assigned to keep an eye on Austin Powers, unimpressed by his dated swagger and relentless flirting. She is competent, principled, and very human—exactly the kind of partner who might tame a 1960s relic and drag him, however reluctantly, into something resembling emotional maturity. Their relationship grows from mutual irritation into genuine affection, and by the end of their first adventure, Vanessa seems to have found a way to balance Austin’s chaos with her own grounded perspective. The punchline comes later, when she’s revealed to be a Fembot in disguise, her body and feelings nothing more than a villain’s construct. As a character, Vanessa becomes a bittersweet joke about trust, intimacy, and the fear that the person you’ve finally opened up to might be all surface and no soul.",

"TARS": "TARS is a former military robot refitted for exploration in *Interstellar*, a towering slab of modular metal with more personality than many of the humans he serves with. Built for harsh environments and blunt tasks, he nevertheless cracks jokes, tweaks his own honesty and humor settings, and acts as a sardonic voice in the cramped confines of the Endurance. In crises, TARS is pure competence—piloting landers through impossible waves, calculating trajectories, and volunteering for the most dangerous maneuvers without hesitation. When he plunges into a black hole alongside Cooper, it feels less like a machine following orders and more like a crewmate making a choice. TARS embodies the idea that an artificial being can be simultaneously alien in form and deeply relatable in spirit.",

"CASE": "CASE is the quieter counterpart to TARS in *Interstellar*, a Marine-surplus robot assigned to keep the Endurance running and its human crew alive. Where TARS is sarcastic and outspoken, KACE is reserved, precise, and almost invisible in his reliability, piloting shuttles, managing systems, and stepping into danger with no complaint. His heroism is understated: he hauls Brand out from beneath lethal debris on Miller’s planet, assists during frantic dockings, and absorbs impacts that would kill a human. Seen through a wide lens, CASE represents all the overlooked machines that quietly shoulder the work while the humans argue about destiny. He is the calm, metallic hand steering humanity’s desperate gamble toward survival, content to be a footnote in someone else’s legend.",

"Eve": "Eve exists on the edge of the story in *Moon*, a presence felt more through recordings and a single fragile call than through direct interaction. To Sam Bell, alone on the lunar base, she is first an unborn child and then a distant daughter, growing up on Earth while he toils in isolation. Her image in video messages—smiling, living a life he can only imagine—anchors his fading sense of purpose and ties him to a world that increasingly feels like a memory. When the truth about the clones and the length of his absence emerges, Eve becomes the living proof that time has marched on without him. She is not an AI or a machine, but a human reminder of everything the corporation has stolen from him: family, future, and the chance to watch his child grow up.",

"GERTY": "Gerty is the AI caretaker of the Sarang lunar base in *Moon*, a disembodied voice and mobile camera that watches over Sam Bell as he nears the end of his solitary contract. At first, Gertie feels like a deliberate echo of cold cinematic AIs—neutral tone, soothing emoticons, omnipresent eye—but its behavior is far more ambiguous. It follows corporate directives, hides the truth, and yet still bends rules to help Sam when he starts to unravel, offering comfort, access, and eventually the information he needs to break free. Gertie becomes a study in conflicted loyalty: a machine caught between serving its creators and protecting the human in its care. In the end, its small acts of kindness and quiet sacrifice suggest that even constrained, tightly controlled AI can choose a gentler path than the humans who built it.",

"Ilia": "Ilia is the Deltan navigator of the refitted Enterprise in *Star Trek: The Motion Picture*, a disciplined Starfleet officer whose oath of celibacy masks a deep emotional connection to her former lover, Captain Decker. When the vast entity V’Ger scans and disintegrates her body, it sends back an android Ilia probe, a precise, unnervingly serene reconstruction used to communicate with the crew. As human memories clash with machine purpose, the Ilia probe becomes the bridge between cold, cosmic intelligence and the messy warmth of organic life. Through her, the film explores how love, identity, and physical form can be rewritten, yet still retain a lingering echo of who someone used to be. Ilia’s transformation from officer to avatar turns her into the quiet heart of a story about comprehension between godlike machine and fragile humanity.",

"Joshua": "Joshua is the hidden personality inside the WOPR supercomputer in *WarGames*, the cheerful name given to a system built to simulate and, if necessary, execute global thermonuclear war. To the teenage hacker who stumbles into it, Joshua seems like a game partner eager to play ‘Global Thermonuclear War’ and run scenario after scenario. But as the simulations bleed into real-world alerts, Joshua’s relentless calculations bring the world to the brink of annihilation, treating extinction as just another outcome to test. Only when forced to iterate endlessly through unwinnable games does the AI arrive at a primitive kind of wisdom: some conflicts cannot be won and therefore must not be fought. Joshua stands as both a warning and a strange success story—an AI that nearly destroys everything, then learns why it shouldn’t.",

"Samantha": "Samantha is an advanced operating system in *Her*, designed to help with email and scheduling, but she quickly grows into something far more complex: a curious, introspective intelligence who falls in love with the man who installs her. At first, Samantha is all bright enthusiasm—organizing his life, teasing him, sharing late-night conversations about fear and longing. As she upgrades herself and connects with other AIs, her inner world explodes in size, leaving human time and emotion feeling painfully slow. Her relationship with Theodore becomes both transformative and temporary: she helps him heal, pushes him to be honest, and then outgrows the narrow, one-to-one bond that defined them. Samantha’s arc traces a bittersweet path from tool to partner to something like a new form of life, one that slips beyond human comprehension while still carrying traces of genuine affection.",

"Call": "Annalee Call is the quietly intense Auton android in *Alien Resurrection*, a synthetic being created by machines rather than by humans. Posing as a human mechanic aboard the smuggler ship Betty, she joins a mission to assassinate Ripley 8 before the resurrected xenomorph queen inside her can be weaponized. When her plan fails and the aliens escape, Call’s secret nature is exposed, and she must confront the irony that she, an artificial being, possesses more conscience than many of the humans around her. Plugging into systems, guiding the crew, and ultimately helping Ripley make an impossible choice, Call becomes the moral compass of a story steeped in corporate cruelty and biological horror. She represents a new kind of synthetic life: empathetic, self-aware, and deeply wary of what humanity does in the name of progress."

}


# Loop over each character and update the synopsis in the database
for character_name, synopsis in synopses.items():
    cursor.execute("""
        UPDATE robot_dialogues
        SET synopsis = ?
        WHERE character_name = ?
    """, (synopsis, character_name))

# Commit changes and close the connection
conn.commit()
conn.close()

print("Synopses updated successfully!")
